[book]
authors = ["Dylan Huynh", "Nicole Chun", "Jeremy Le", "Alex Lee"]
language = "en"
multilingual = false
src = "src"
title = "DevSoc Training Program Exercises"

[output.html]
site-url = "/book/"